services:
  homeassistant:
    image: homeassistant/home-assistant:latest
    container_name: homeassistant_smarthome
    restart: unless-stopped
    ports:
      - "8123:8123"
    volumes:
      - homeassistant_data:/config