services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_monitoring
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus