services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana_monitoring
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana