services:
  nginx:
    image: nginx:latest
    container_name: nginx_reverseproxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx_data:/etc/nginx/conf.d
      - nginx_html:/usr/share/nginx/html